language: go
go:
- "1.9"
- "1.10"
- "1.11"
- "master"
matrix:
  allow_failures:
  - go: "master"
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- openssl aes-256-cbc -K $encrypted_ecf501240fa0_key -iv $encrypted_ecf501240fa0_iv
  -in client_secret.json.enc -out client_secret.json -d
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
